# Supabase CLI Configuration
# Docs: https://supabase.com/docs/reference/cli/config

[api]
port = 54321

[studio]
port = 3000
enabled = true

[inbucket]
port = 54325

[db]
port = 54322

[functions]
port = 54324

[analytics]
enabled = false
