apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: tuneton
type: Opaque
data:
  # Default username: admin (base64 encoded)
  admin-username: YWRtaW4=
  # Default password: admin (base64 encoded)
  admin-password: YWRtaW4=
