apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: tuneton
type: Opaque
data:
  # Default username: postgres
  username: cG9zdGdyZXM=
  # Default password: postgres (in production, use a secure password and encrypt it)
  password: cG9zdGdyZXM=
