apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: tuneton
type: Opaque
data:
  # Default username: guest (base64 encoded)
  username: Z3Vlc3Q=
  # Default password: guest (base64 encoded)
  password: Z3Vlc3Q=
