apiVersion: v1
kind: Service
metadata:
  name: audio-processing-service
  namespace: tuneton
  labels:
    app: audio-processing-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: audio-processing-service
